#!/usr/bin/with-contenv bash

# If the first run completed successfully, we are done
if [ -e /.firstRunComplete ]; then
    exit 0
fi

# Setup user/group ids
if [ ! -z "${NODERED_UID}" ]; then
    if [ ! "$(id -u node-red)" -eq "${NODERED_UID}" ]; then
        # usermod likes to chown the home directory, so create a new one and use that
        # However, if the new UID is 0, we can't set the home dir back because the
        # UID of 0 is already in use (executing this script).
        if [ ! "${NODERED_UID}" -eq 0 ]; then
            mkdir /tmp/temphome
            usermod -d /tmp/temphome node-red
        fi

        # Change the UID
        usermod -o -u "${NODERED_UID}" node-red

        # Cleanup the temp home dir
        if [ ! "${NODERED_UID}" -eq 0 ]; then
            usermod -d /data node-red
            rm -Rf /tmp/temphome
        fi
    fi
fi

if [ ! -z "${NODERED_GID}" ]; then
    if [ ! "$(id -g node-red)" -eq "${NODERED_GID}" ]; then
        groupmod -o -g "${NODERED_GID}" node-red
    fi
fi

# Update ownership of dirs we need to write
if [ "${CHANGE_CONFIG_DIR_OWNERSHIP,,}" = "true" ]; then
    /usr/bin/find /usr/src/node-red \! \( -uid $(id -u node-red) -gid $(id -g node-red) \) -print0 | xargs -0 chown -h node-red:node-red
    /usr/bin/find /data \! \( -uid $(id -u node-red) -gid $(id -g node-red) \) -print0 | xargs -0 chown -h node-red:node-red
fi

touch /.firstRunComplete
echo "Node-Red first run setup complete"
